### ISSUE TITLE
MintPlayer.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering timed out after 30000ms because the boot function in 'jobdeskcom/dist/server/main.js' returned a promise that did not resolve or reject.

### ISSUE THREAD

**Issue by SabirHossain** [MintPlayer/MintPlayer.AspNetCore.SpaServices.Routing#40]

**Comment by PieterjanDeClippel** [comment]
Can you show your [`main.server.ts`](https://github.com/MintPlayer/MintPlayer/blob/master/MintPlayer.Web/ClientApp/src/main.server.ts)? Did you follow [this guide](https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-2022-version-7aaed8157976)?
